# Generated by Django 3.0.4 on 2020-03-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_api', '0002_auto_20200317_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
